In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [5]:
ar = np.array(l)

In [6]:
ar

array([1, 2, 3, 4])

In [7]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(1)

array(1)

In [10]:
a = [2,3,4]

In [11]:
np.asanyarray(a)

array([2, 3, 4])

In [14]:
b = np.matrix(l)

In [15]:
b

matrix([[1, 2, 3, 4]])

In [16]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [17]:
a = np.array(l)

In [18]:
a

array([1, 2, 3, 4])

In [19]:
c=a

In [20]:
c

array([1, 2, 3, 4])

In [21]:
array([1,2,3,4])

NameError: name 'array' is not defined

In [23]:
a

array([1, 2, 3, 4])

In [24]:
c[0] = 100

In [25]:
c

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [27]:
d = np.copy(a)

In [28]:
d

array([100,   2,   3,   4])

In [29]:
a

array([100,   2,   3,   4])

In [30]:
a[1] = 400

In [31]:
a

array([100, 400,   3,   4])

In [32]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
iterable = (i*i for i in range(5))

In [36]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring('234 234' , sep=' ')

array([234., 234.])

In [39]:
np.fromstring('4,5', sep = ',')

array([4., 5.])

In [40]:
#Numpy - Data Types.

In [41]:
l = [2, 3,4,5,6]

In [42]:
ar = np.array(1)

In [43]:
ar 

array(1)

In [44]:
ar.ndim

0

In [45]:
ar2 = np.array([[1,2,3,4], [2,3,4,5]])

In [46]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [47]:
ar2.ndim

2

In [48]:
ar2.size

8

In [49]:
ar

array(1)

In [50]:
array([[1,2,3,4],
       [2,3,4,5]])

NameError: name 'array' is not defined

In [51]:
ar.shape

()

In [52]:
ar2.shape

(2, 4)

In [53]:
ar.dtype

dtype('int64')

In [54]:
ar2.dtype

dtype('int64')

In [55]:
ar22 = np.array([(1.4, 45, 45), (23,45,66)])

In [56]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [57]:
ar22.dtype

dtype('float64')

In [60]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
list(range(0.1, 5))

TypeError: 'float' object cannot be interpreted as an integer

In [62]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [64]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [66]:
np.linspace(1,5,30)

array([1.        , 1.13793103, 1.27586207, 1.4137931 , 1.55172414,
       1.68965517, 1.82758621, 1.96551724, 2.10344828, 2.24137931,
       2.37931034, 2.51724138, 2.65517241, 2.79310345, 2.93103448,
       3.06896552, 3.20689655, 3.34482759, 3.48275862, 3.62068966,
       3.75862069, 3.89655172, 4.03448276, 4.17241379, 4.31034483,
       4.44827586, 4.5862069 , 4.72413793, 4.86206897, 5.        ])

In [69]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [70]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [73]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [79]:
ar4=np.zeros((3,4,2,3))

In [80]:
ar4.ndim

4

In [81]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [82]:
np.ones(4)

array([1., 1., 1., 1.])

np.ones((2,3))

In [83]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
on = 

In [84]:
np.empty((3,5))

array([[4.64898378e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [86]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [87]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [89]:
np.logspace(2,5, 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [91]:
np.random.randn(3,4)

array([[ 0.00805058, -0.24533833, -0.15448461,  1.64535283],
       [ 1.46925386, -0.92624794,  2.2550219 ,  0.70355432],
       [ 0.8847748 ,  0.33615191, -1.30588881, -3.33658119]])

In [92]:
arr=np.random.randn(3,4)

In [93]:
arr

array([[-0.83729219,  0.71459991, -0.89295896,  0.24044135],
       [ 0.49463197,  1.44257758, -0.81656609,  0.15662318],
       [-0.89747988,  0.79811824,  0.46513572, -0.77886006]])

In [94]:
import pandas as pd

In [96]:
pd.DataFrame(arr)

0         1         2         3
0 -0.837292  0.714600 -0.892959  0.240441
1  0.494632  1.442578 -0.816566  0.156623
2 -0.897480  0.798118  0.465136 -0.778860

In [97]:
np.random.randint(1,110,(3,4))

array([[  6,  92, 108,  44],
       [ 25,  25,  66,  61],
       [ 13,  70,  64,   8]])

In [101]:
pd.DataFrame(np.random.randint(1,100, (40,5)))

0   1   2   3   4
0    4  69  17  75  27
1   12  30  67  14  59
2   43  19  88   7  87
3   82   6  29  86  56
4   24  43  45  69   1
5   96  53  61  86  92
6   20  16  24  33  60
7   13   3   9  27  80
8   65  86  40  19  87
9   45  42  65  33  14
10  57  25  73  36  67
11  40  44  56  32  37
12  97  25  49   7  30
13  69  66  17  23  22
14  99  12  92  13  94
15  19  48  46  90  93
16  82  73  97  89  20
17  66  82  40  11  24
18  77  67   4  93  96
19  15  76  18  95  41
20  26  53  41  77  77
21  72  48  88  23  16
22  20  25  21  97   9
23  77  30  29  73   4
24  15  32  92  78   1
25  11  32  82  45  43
26  45  68  85  41  98
27  24  10  41   1   7
28  47  37  32   3  71
29  89  82  66  26  46
30   3  47  53  83  85
31  72   5  44  72  14
32  31  43  92  55  42
33  17  46  55  49  20
34  16   2  34  26  88
35  33  13  47  39  73
36  52  76  73  27  40
37  98  60  82   9  54
38  68  95  64  43  73
39  20  74  58  53   7

In [102]:
arr = np.random.rand(3,4)

In [103]:
arr

array([[0.17425549, 0.4906483 , 0.19029033, 0.41080707],
       [0.52011493, 0.02663888, 0.70135301, 0.32812968],
       [0.664743  , 0.76736708, 0.82754595, 0.34867086]])

In [106]:
arr1 = arr.reshape(6,2)

arr1

In [107]:
arr1

array([[0.17425549, 0.4906483 ],
       [0.19029033, 0.41080707],
       [0.52011493, 0.02663888],
       [0.70135301, 0.32812968],
       [0.664743  , 0.76736708],
       [0.82754595, 0.34867086]])

In [108]:
arr1[1]

array([0.19029033, 0.41080707])

In [110]:
arr1[1][1]

0.4108070679349939

In [111]:
arr1[2:5,1]

array([0.02663888, 0.32812968, 0.76736708])

In [114]:
arr=np.random.randint(1,100, (5,5))

In [115]:
arr

array([[35, 91, 55, 21, 66],
       [72, 69,  7, 19, 26],
       [60, 11, 41, 88, 93],
       [58, 60, 44, 59, 36],
       [74, 34, 96, 45, 45]])

In [117]:
arr[arr>50]

array([91, 55, 66, 72, 69, 60, 88, 93, 58, 60, 59, 74, 96])

In [118]:
arr>50

array([[False,  True,  True, False,  True],
       [ True,  True, False, False, False],
       [ True, False, False,  True,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True, False, False]])

In [119]:
arr

array([[35, 91, 55, 21, 66],
       [72, 69,  7, 19, 26],
       [60, 11, 41, 88, 93],
       [58, 60, 44, 59, 36],
       [74, 34, 96, 45, 45]])

In [120]:
arr[2:4,[1,2]]

array([[11, 41],
       [60, 44]])

In [121]:
arr[0][0] = 5000

In [122]:
arr

array([[5000,   91,   55,   21,   66],
       [  72,   69,    7,   19,   26],
       [  60,   11,   41,   88,   93],
       [  58,   60,   44,   59,   36],
       [  74,   34,   96,   45,   45]])

In [123]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [124]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [125]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [126]:
arr1+arr2

array([[3, 3, 4],
       [4, 3, 4],
       [3, 2, 2]])

In [127]:
arr1-arr2

array([[ 1, -1,  0],
       [ 0,  1,  0],
       [-1,  0,  0]])

In [128]:
arr1/arr2

array([[2. , 0.5, 1. ],
       [1. , 2. , 1. ],
       [0.5, 1. , 1. ]])

In [129]:
arr1*arr2

array([[2, 2, 4],
       [4, 2, 4],
       [2, 1, 1]])

In [130]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [131]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [132]:
arr1@arr2

array([[ 8,  7,  8],
       [10,  8, 10],
       [ 5,  4,  5]])

In [133]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [134]:
arr1 +100

array([[102, 101, 102],
       [102, 102, 102],
       [101, 101, 101]])

In [135]:
arr1**2

array([[4, 1, 4],
       [4, 4, 4],
       [1, 1, 1]])

In [137]:
#broadcasting- numpy 

In [138]:
arr= np.zeroes((4,4))

AttributeError: module 'numpy' has no attribute 'zeroes'

In [142]:
arr

array([[5000,   91,   55,   21,   66],
       [  72,   69,    7,   19,   26],
       [  60,   11,   41,   88,   93],
       [  58,   60,   44,   59,   36],
       [  74,   34,   96,   45,   45]])

In [143]:
arr + row 

NameError: name 'row' is not defined

In [145]:
row.T

NameError: name 'row' is not defined

In [146]:
col = np.array([[1,2,3,4]])

In [147]:
col.T+arr

ValueError: operands could not be broadcast together with shapes (4,1) (5,5) 

In [148]:
col

array([[1, 2, 3, 4]])

In [149]:
arr

array([[5000,   91,   55,   21,   66],
       [  72,   69,    7,   19,   26],
       [  60,   11,   41,   88,   93],
       [  58,   60,   44,   59,   36],
       [  74,   34,   96,   45,   45]])

In [150]:
arr1 = np.random.randint(1,4,  (3,4))

In [151]:
arr1

array([[1, 2, 2, 3],
       [3, 1, 1, 2],
       [1, 1, 1, 3]])

In [152]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356, 1.73205081],
       [1.73205081, 1.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.        , 1.73205081]])

In [153]:
np.exp(arr1)

array([[ 2.71828183,  7.3890561 ,  7.3890561 , 20.08553692],
       [20.08553692,  2.71828183,  2.71828183,  7.3890561 ],
       [ 2.71828183,  2.71828183,  2.71828183, 20.08553692]])

In [154]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.30103   , 0.47712125],
       [0.47712125, 0.        , 0.        , 0.30103   ],
       [0.        , 0.        , 0.        , 0.47712125]])