In [1]:
#numpy - array manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[5, 3, 4, 9],
       [7, 5, 6, 4],
       [6, 8, 1, 3]])

In [5]:
arr.reshape(2,6)

array([[5, 3, 4, 9, 7, 5],
       [6, 4, 6, 8, 1, 3]])

In [6]:
arr.reshape(2, -242342)

array([[5, 3, 4, 9, 7, 5],
       [6, 4, 6, 8, 1, 3]])

In [8]:
arr.T

array([[5, 7, 6],
       [3, 5, 8],
       [4, 6, 1],
       [9, 4, 3]])

In [9]:
arr

array([[5, 3, 4, 9],
       [7, 5, 6, 4],
       [6, 8, 1, 3]])

In [10]:
arr.flatten()

array([5, 3, 4, 9, 7, 5, 6, 4, 6, 8, 1, 3])

In [11]:
arr1 = np.array([1,2,3,4,5])

In [12]:
arr1.ndim

1

In [14]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [16]:
arr

array([[5, 3, 4, 9],
       [7, 5, 6, 4],
       [6, 8, 1, 3]])

In [17]:
np.squeeze(arr)

array([[5, 3, 4, 9],
       [7, 5, 6, 4],
       [6, 8, 1, 3]])

In [18]:
data = np.array([[1],[2], [3]])

In [19]:
data

array([[1],
       [2],
       [3]])

In [20]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
array([1,2,3])

NameError: name 'array' is not defined

In [22]:
arr1

array([1, 2, 3, 4, 5])

In [23]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [25]:
np.roll(arr1, 2)

array([4, 5, 1, 2, 3])

In [26]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
#nupmy - binary operation

In [3]:
arr1 = np.random.randint(1,10,(3,4))

NameError: name 'np' is not defined

In [4]:
arr2 = np.random.randint(1,10,(3,4))

NameError: name 'np' is not defined

In [7]:
arr1+arr2

NameError: name 'arr1' is not defined

In [ ]:
arr1/arr2

In [8]:
arr.1-arr2

SyntaxError: invalid syntax (2231376978.py, line 1)

In [9]:
arr%arr2

NameError: name 'arr' is not defined

In [10]:
arr1**arr2

NameError: name 'arr1' is not defined

In [11]:
arr1 & arr2

NameError: name 'arr1' is not defined

In [12]:
arr1

NameError: name 'arr1' is not defined

In [13]:
arr2

NameError: name 'arr2' is not defined

In [14]:
~arr1

NameError: name 'arr1' is not defined

In [15]:
arr1|arr2

NameError: name 'arr1' is not defined

In [16]:
arr1>arr2

NameError: name 'arr1' is not defined

In [17]:
#string functions 

In [18]:
np.array(['sudh',"kumar"])

NameError: name 'np' is not defined

In [19]:
arr

NameError: name 'arr' is not defined

In [20]:
np.char.title(arr)

NameError: name 'np' is not defined

In [21]:
np.char.capitalize(arr)

NameError: name 'np' is not defined

In [22]:
#Numpy - mathmatical function

In [23]:
arr1

NameError: name 'arr1' is not defined

In [24]:
np.sin(arr1)

NameError: name 'np' is not defined

In [25]:
np.cos(arr1)

NameError: name 'np' is not defined

In [26]:
np.tan(arr1)

NameError: name 'np' is not defined

In [27]:
np.log10(arr1)

NameError: name 'np' is not defined

In [28]:
np.exp(arr1)

NameError: name 'np' is not defined

In [29]:
np.sqrt(arr1)

NameError: name 'np' is not defined

In [30]:
np.power(arr1, 2)

NameError: name 'np' is not defined

In [31]:
np.mean(arr1)

NameError: name 'np' is not defined

In [32]:
np.median(arr1)

NameError: name 'np' is not defined

In [33]:
np.std(arr1)

NameError: name 'np' is not defined

In [34]:
np.var(arr1)

NameError: name 'np' is not defined

In [35]:
np.min(arr1)

NameError: name 'np' is not defined

In [36]:
import numpy as np

In [37]:
np.min(arr1)

NameError: name 'arr1' is not defined